/** Sección Esquema: política, keys, ubicaciones, personas y datos del esquema. */
export const esquema = {
  sobre: 'Sobre este esquema',
  politica: 'Política de gasto',
  firmasNecesarias: 'Firmas necesarias',
  kDeN: (k: number, n: number) => `${k} de ${n}`,
  pistaFirmas: 'Cuántas keys hacen falta para gastar.',
  singleSig: 'Single-sig: basta con una key. Añade otra para convertirlo en multisig.',
  keys: (n: number) => `Keys (${n})`,
  key: 'Key',
  conPassphrase: (fuerza: string) => `+ passphrase ${fuerza}`,
  sinIndicar: 'sin indicar',
  xpub: 'xpub',
  pistaXpub: 'Tiene su xpub: entra en el descriptor',
  verificada: 'verificada',
  pistaVerificada: 'Derivación verificada con una herramienta independiente',
  nombreYDescripcion: 'Nombre y descripción del esquema',
  nombre: 'Nombre del esquema',
  descripcion: 'Descripción',
  pistaDescripcion: 'Para qué sirve este esquema, notas…',
  avisos: 'Avisos',
  errores: 'Errores que corregir',
  analisisEnPausa: 'Mientras haya errores, el análisis está en pausa.',
  tiposElemento: { stateful: 'Dispositivo', stateless: 'Stateless', artifact: 'Backup' },
  queAnadir: 'Qué añadir',
  donde: 'Dónde',
  ubicaciones: (n: number) => `Ubicaciones (${n})`,
  ubicacion: 'Ubicación',
  dispositivo: 'Dispositivo',
  backup: 'Backup',
  anadirEn: (lugar: string | null) => `Añadir dispositivo o backup en ${lugar ?? 'esta ubicación'}`,
  pistaAnadirAqui: 'Añadir dispositivo o backup aquí',
  vacia: 'Vacía',
  personas: (n: number) => `Personas (${n})`,
  persona: 'Persona',
  ubicacionesPlural: ['ubicación', 'ubicaciones'] as const,
  entraEn: (ubicaciones: string) => `Entra en ${ubicaciones}`,
  noEntra: 'No entra en ninguna ubicación',
  sabeDeMemoria: 'Sabe de memoria',
};
