/** Fichas de cada elemento (columna izquierda): persona, backup, dispositivo, ubicación, key y sus campos. */

export const campos = {
  sinOpciones: 'No hay opciones.',
  nombre: 'Nombre',
  ubicacion: 'Ubicación',
};

export const persona = {
  tipo: 'Persona',
  roles: { owner: 'Titular', heir: 'Heredero/a', custodian: 'Custodio/a', other: 'Otra persona' },
  rol: 'Rol',
  unicoTitular: 'Es el único titular: asigna otro antes de cambiarle el rol.',
  sabeDeMemoria: 'Sabe de memoria',
  pistaMemoria: 'Lo que recuerda sin apuntarlo. Un atacante que le coaccione lo obtiene.',
  puedeEntrar: 'Puede entrar en',
  enNingunSitio: 'En ningún sitio. Los accesos se editan desde cada ubicación.',
  siempre: 'siempre',
  trasFallecer: 'tras fallecer',
  siNoPuede: 'si no puede actuar',
  desconocida: '?',
  eliminar: 'Eliminar persona',
  haceFaltaTitular: 'Tiene que haber al menos un titular.',
};

export const backup = {
  tipo: 'Backup',
  soportes: { metal: 'Metal (placa)', washers: 'Arandelas', paper: 'Papel', digital: 'Digital', other: 'Otro' },
  soporte: 'Soporte',
  queContiene: 'Qué contiene',
  pistaContenido: 'Un backup tiene que contener algo: el último elemento no se puede quitar.',
  cifrado: 'Cifrado',
  conContrasena: 'Cifrado con contraseña',
  pistaContrasena: 'Quien sepa la contraseña se indica en la ficha de cada persona (o en otro backup donde esté apuntada).',
  tambienCon: 'También cifrado con',
  pistaTambien: 'Otros secretos necesarios para leerlo (p. ej. un fichero cifrado con la clave de un dispositivo).',
  eliminar: 'Eliminar backup',
};

export const cartera = {
  derivacion: 'Derivación',
  pistaDerivacion: "m/48'/0'/0'/2'",
  errorDerivacion: "Una ruta como m/48'/0'/0'/2' (con ' o h para las endurecidas).",
  xpub: 'Xpub',
  pistaXpub: 'xpub6…  (también zpub, Zpub, tpub…)',
  convertida: (escrita: string, guardada: string) => `Escrita como ${escrita}: se guarda como ${guardada}, que es la misma clave.`,
};

export const hardware = {
  dispositivosDelEsquema: 'Dispositivos de este esquema',
  descatalogado: ' (descatalogado)',
  otro: 'Otro (escribir a mano)',
  fabricante: 'Fabricante',
  fabricanteDesconocido: 'Fabricante desconocido',
  coaccion: { decoy: 'señuelo', wipe: 'borrado' },
  antiExfil: 'anti-exfil',
  conCoaccion: (tipos: readonly string[]) => `PIN de coacción (${tipos.join(' y ')})`,
  sinCoaccion: 'sin PIN de coacción',
  registraMultisig: 'registra multisig',
  noRegistraMultisig: 'no registra multisig',
  segunCatalogo: (fecha: string, rasgos: readonly string[]) => `Según el catálogo (${fecha}): ${rasgos.join(' · ')}.`,
  fuente: 'Fuente',
};

export const dispositivo = {
  tipo: 'Dispositivo',
  tipos: { stateful: 'Guarda keys', stateless: 'Stateless' },
  coaccion: {
    ambas: 'Bajo amenaza das otro PIN que abre un wallet señuelo o borra el dispositivo.',
    senuelo: 'Bajo amenaza das otro PIN que abre un wallet señuelo.',
    borrado: 'Bajo amenaza das otro PIN que borra el dispositivo.',
    generico: 'Bajo amenaza das otro PIN (señuelo o borrado).',
    noLaEvita: 'Encarece la llave inglesa, pero no la evita: un atacante informado puede saber que existe.',
  },
  modelo: 'Modelo',
  fabricante: 'Fabricante',
  nombreModelo: 'Nombre del modelo',
  opcional: 'opcional',
  firmware: 'Firmware instalado',
  pistaFirmware: 'p. ej. 5.6.0',
  tipoTitulo: 'Tipo',
  tipoDispositivo: 'Tipo de dispositivo',
  pistaStateful: 'Guarda las keys en su memoria (Coldcard, Jade, Passport…). Quien lo tenga y sepa el PIN puede firmar.',
  pistaStateless: 'No guarda nada: hay que cargarle la semilla cada vez (SeedSigner, Krux…).',
  keysQueGuarda: 'Keys que guarda',
  keysQueFirmas: 'Keys que firmas con él',
  sinIndicar: 'Sin indicar',
  pistaSinIndicar: 'Volver a asumir que cualquier semilla puede pasar por él',
  cargasSinIndicar: 'Sin indicar: asumimos que cualquier frase semilla que tengas escrita puede pasar por él.',
  cargas: 'Semillas que cargas en él para firmar.',
  antiExfil: 'Tiene anti-exfil: un firmware malicioso no podría filtrarlas en las firmas (si el software con el que firmas lo usa).',
  sinAntiExfil: 'Un firmware malicioso podría filtrarlas en las firmas.',
  seguridad: 'Seguridad y funciones',
  pin: 'Protegido por PIN',
  pistaPin: 'Quien sepa el PIN se indica en la ficha de cada persona.',
  pinCoaccion: 'PIN de coacción configurado',
  semillasExternas: 'Firma con semillas externas',
  pistaSemillasExternas: 'Puede cargar temporalmente otra semilla para firmar con ella.',
  multisigRegistrado: 'Multisig registrado',
  pistaMultisig: 'Guarda la configuración del wallet, y por tanto todas las xpubs.',
  eliminar: 'Eliminar dispositivo',
};

export const key = {
  tipo: 'Key',
  fuentes: {
    'device-rng': 'RNG de dispositivo',
    'software-rng': 'RNG de software',
    dice: 'Dados',
    coin: 'Moneda',
    cards: 'Cartas',
    unknown: 'Desconocido',
  },
  software: 'Software',
  tiradas: 'nº tiradas',
  quitarFuente: 'Quitar fuente',
  fuerzas: { weak: 'Débil', phrase: 'Frase', random: 'Aleatoria larga' },
  pistasFuerza: {
    unset: 'Sin indicar: se trata como débil. Elige cómo es para que el análisis sea realista.',
    weak: 'Una palabra, un nombre o una fecha. Con la semilla en la mano, se adivina casi gratis.',
    phrase: 'Varias palabras elegidas por ti. Con la semilla, adivinarla exige mucho cómputo y algo de suerte.',
    random: 'Generada al azar y larga (p. ej. 6 o más palabras con dados). No se puede adivinar.',
  },
  enMemoria: 'en memoria',
  fraseSemilla: 'frase semilla',
  requierePassphrase: 'Requiere passphrase',
  pistaPassphrase: 'Sin la passphrase, la semilla sola no sirve.',
  comoEsPassphrase: 'Cómo es la passphrase',
  enLaCartera: 'En la cartera',
  fingerprint: 'Fingerprint',
  opcional: 'opcional',
  pistaCartera:
    'Opcional: con las xpubs de todas las keys, Esquema muestra el descriptor y la primera dirección. Más cómodo: importar el descriptor desde Esquema.',
  dondeEsta: 'Dónde está',
  enNingunSitio: 'En ningún sitio: si nadie la sabe de memoria, esta key está perdida.',
  entropia: 'Entropía',
  fuente: 'Fuente',
  pistaMezcla: 'Si mezclas varias fuentes, basta con que una sea buena… salvo que el dispositivo que las mezcla esté comprometido.',
  /** «… una guía paso a paso es {enlace}, de Estudio Bitcoin.» */
  moneda: { antes: 'Hay varias formas de crear la semilla a mano con una moneda; una guía paso a paso es', enlace: 'semilla-moneda', despues: ', de Estudio Bitcoin.' },
  generacion: 'Generación',
  estaEn: (dispositivo: string) => `Esta key está en ${dispositivo}. ¿Se generó ahí?`,
  estaEnVarios: 'Esta key está en varios dispositivos. ¿Se generó en alguno?',
  siRellenar: 'Sí, rellenar',
  pistaRellenar: 'Rellena la entropía (RNG del dispositivo) y el fabricante, modelo y firmware con que se generó.',
  aMano: 'Calculada a mano',
  pistaAMano: 'Sin dispositivo ni software que haya derivado la semilla.',
  generadaEn: 'Generada en',
  fabricanteOSoftware: 'Fabricante o software',
  nombreModelo: 'Nombre del modelo',
  firmware: 'Firmware con el que se generó',
  pistaFirmware: 'p. ej. 5.6.0',
  firmwareDeEntonces: 'Cuenta el firmware de cuando se generó la semilla, no el que tenga ahora el dispositivo.',
  verificada: 'Verificada de forma independiente',
  pistaVerificada: 'Comprobaste con otra herramienta que la semilla sale de tu entropía (p. ej. tus tiradas de dados).',
  verificarSinEntropiaPropia:
    'Verificar solo protege si hay una fuente tuya (dados, moneda o cartas): demuestra que la semilla sale de esa entropía, no que la entropía sea buena. Si solo hay RNG (de un dispositivo, de un software o desconocido), un fallo en él la compromete igual.',
  verificarConRng:
    'Mezclando un RNG con tus tiradas, normalmente no se puede verificar: la parte del RNG es secreta y otra herramienta no puede recalcularla. Para poder verificar, genera la frase semilla solo con tu entropía (dados o moneda) y recalcúlala en otra herramienta.',
  eliminar: 'Eliminar key',
  haceFaltaKey: 'Tiene que haber al menos una key.',
};

export const ubicacion = {
  tipo: 'Ubicación',
  tipos: { physical: 'Física', device: 'Dispositivo', cloud: 'Nube' },
  pistasTipo: {
    physical: 'Casa, caja del banco… Se ataca con una intrusión y se pierde con un incendio o una inundación.',
    device: 'Portátil, disco duro… Se ataca con robo o malware y se pierde con una avería o un robo.',
    cloud: 'Una cuenta en la nube. Se ataca en remoto (hackeo) y se pierde si se cierra o pierdes el acceso. Cifra lo que guardes aquí.',
  },
  tipoUbicacion: 'Tipo de ubicación',
  proteccion: 'Protección',
  protecciones: { none: 'Ninguna', 'home-safe': 'Caja fuerte', 'bank-box': 'Caja del banco' },
  pistasProteccion: {
    none: 'Una casa, un piso, una oficina… Entrar sin nadie presente cuesta poco.',
    'home-safe':
      'Una caja fuerte doméstica: hay que encontrarla y forzarla. Si está dentro de casa, el robo exige entrar en ambas, y un incendio o una inundación en casa también le llegan.',
    'bank-box':
      'Una caja de seguridad en un banco: lo más difícil de asaltar. Para obligarte a abrirla hay que llevarte allí en horario, y su cámara acorazada resiste mucho mejor un incendio o una inundación.',
  },
  contieneOtras: 'Dentro de esta ubicación hay otras, así que no puede ir dentro de ninguna:',
  dentroDe: 'Dentro de',
  pistaDentroDe: 'P. ej. la caja fuerte, dentro de Casa: para llegar a ella hay que entrar primero en la casa.',
  porSuCuenta: 'Ninguna: está por su cuenta',
  quienEntra: 'Quién puede entrar',
  acceso: 'Acceso',
  nadie: 'Nadie tiene acceso: lo que haya aquí es inalcanzable.',
  pistaNoPuede: '"No puede actuar" = incapacidad o fallecimiento (p. ej. poder notarial preventivo o tutela).',
  siempre: 'Siempre',
  trasFallecer: (persona: string) => `Tras fallecer ${persona}`,
  siNoPuede: (persona: string) => `Si ${persona} no puede actuar`,
  quitarAcceso: 'Quitar acceso',
  queHay: 'Qué hay aquí',
  dispositivo: 'Dispositivo',
  stateless: 'Stateless',
  backup: 'Backup',
  eliminar: 'Eliminar ubicación',
  eliminarCon: (n: number) => `Eliminar ubicación y sus ${n} objetos`,
  haceFalta: 'Tiene que haber al menos una ubicación.',
};

/** Esquema › Descriptor de la cartera. */
export const descriptor = {
  copiado: 'Copiado',
  titulo: 'Descriptor de la cartera',
  importar: 'Importar',
  pistaSinXpubs:
    'Importa el descriptor que ya tienes (Sparrow, Nunchuk, Coldcard…) o pega la xpub en la ficha de cada key: se obtiene el descriptor y la primera dirección, para comprobar que coincide con tu cartera. No permite gastar, pero sí ver tu saldo.',
  imprimir: 'Imprimir o guardar en PDF',
  tipoDireccion: 'Tipo de dirección',
  ordenImporta: 'Con multi (no sortedmulti) el orden de las keys importa: es el de la política.',
  anidados: 'La política tiene umbrales anidados: necesita Miniscript, que todavía no se escribe.',
  privacidad: 'Con las xpubs, este documento deja ver tu saldo y todos tus movimientos. Guárdalo cifrado.',
  descriptor: 'Descriptor',
  testnet: 'testnet',
  copiarDescriptor: 'Copiar el descriptor',
  primeraDireccion: 'Primera dirección de recepción',
  copiarDireccion: 'Copiar la dirección',
  pistaDireccion:
    'Compárala con la primera dirección de recepción de tu cartera (o la que muestra tu dispositivo). Si coincide, el descriptor es el bueno.',
  aImportar: 'Descriptor a importar',
  ejemplo: 'wsh(sortedmulti(2,[a1b2c3d4/48h/0h/0h/2h]xpub…/<0;1>/*,…))#…',
  soloPublico: 'Solo la parte pública: xpubs, fingerprints y derivaciones. Nunca palabras ni claves privadas.',
  importarDescriptor: 'Importar descriptor',
  importado: (emparejadas: readonly string[]) => `Importado: ${emparejadas.join('; ')}.`,
  porOrden:
    'Las emparejadas por orden pueden no ser la key que crees: comprueba en la ficha de cada una que el fingerprint es el de su dispositivo o su backup, o corrige los nombres.',
};
